name: CI Branch

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:

  ci-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    with:
      caching: true
      build_tasks: build
    secrets: inherit
