name: CI Kronicle Metadata

on:
  push:
    branches:
      - '*'

jobs:

  ci-kronicle-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Set up JDK 17 🏗
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper 👀
        uses: gradle/wrapper-validation-action@v1

      - name: Validate kronicle.yaml 👀
        run: ./gradlew validateKronicleMetadata
