name: CI Main

on:
  push:
    branches:
      - main

jobs:

  ci-tag:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Tag build
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        run: ./gradlew release -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}

  ci-build:
    uses: ./.github/workflows/ci-shared-build.yaml
    needs: ci-tag
    with:
      caching: false
      build_tasks: build
    secrets: inherit
