name: CI Shared

on:
  workflow_call:
    inputs:
      caching:
        description: Whether the job should use caching for Gradle and npm dependencies
        required: true
        type: boolean
      build_tasks:
        description: The space separated names of the Gradle tasks to execute
        required: true
        type: string
      publish_plugins:
        description: Whether the job should publish JARs
        required: true
        type: boolean

jobs:

  ci-build-and-publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@v3
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        if: ${{ inputs.caching }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: |
          ./gradlew ${{ inputs.build_tasks }}

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(./gradlew currentVersion -q -Prelease.quiet)

      - name: Publish Plugins
        if: ${{ inputs.publish_plugins }}
        run: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Checkout main branch
        run: |
          git checkout main

      - name: Set version in documentation
        run: |
          sed -i 's#id "tech.kronicle.dependencies-file" version "[0-9]*\.[0-9]*\.[0-9]*"#id "tech.kronicle.dependencies-file" version "${{ steps.get_version.outputs.VERSION }}"#g' README.md

      - name: Commit and push change to documentation
        run: |
          git config user.email "deploy@kronicle.tech"
          git config user.name "Kronicle Deploy"
          git add README.md
          git commit --allow-empty -m "Update version in documentation to v${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: Clean up Gradle Cache
        if: ${{ inputs.caching }}
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
