name: Publish Plugins

on:
  release:
    types: [created]

jobs:

  publish:
    uses: ./.github/workflows/ci-shared-build-and-publish.yaml
    with:
      caching: false
      build_tasks: build
      publish_plugins: true
    secrets: inherit
